### ISSUE TITLE
It should be no data at this website....

### ISSUE THREAD

**Issue by hellangleZ** [microsoft/Megatron-DeepSpeed#297] opened 2023-11-22 13:48 UTC
/pretrain_gpt_1.3B_seq_parallel.sh: line 151: ds_ssh: command not found
--2023-11-22 03:43:40--  https://the-eye.eu/public/AI/pile_neox/data/BookCorpusDataset_text_document.bin
Resolving the-eye.eu (the-eye.eu)... 162.213.130.6
Connecting to the-eye.eu (the-eye.eu)|162.213.130.6|:443... connected.
HTTP request sent, awaiting response... No data received.
Retrying.

**Comment by zbxxxxxx** [comment] 2023-11-25 03:02
I have also encountered this problem, how should I solve it?

**Comment by zbxxxxxx** [comment] 2023-12-03 14:41
> Same issue. The website https://the-eye.eu/public/AI/ does not have this data path of pile_neox. How can I solve this problem?

我手动下载到本地才解决的，在项目文件找到下载连接，然后用某雷svip才能链接上资源下载

**Comment by hellangleZ** [comment] 2023-12-05 01:44
> > Same issue. The website https://the-eye.eu/public/AI/ does not have this data path of pile_neox. How can I solve this problem?
> 
> 我手动下载到本地才解决的，在项目文件找到下载连接，然后用某雷svip才能链接上资源下载

which link？ I just access this website, there is no this file [/pile_neox/data/BookCorpusDataset_text_document.bin](https://the-eye.eu/public/AI/pile_neox/data/BookCorpusDataset_text_document.bin)

**Comment by zbxxxxxx** [comment] 2023-12-05 02:46
> > > Same issue. The website https://the-eye.eu/public/AI/ does not have this data path of pile_neox. How can I solve this problem?
> > 
> > 
> > 我手动下载到本地才解决的，在项目文件找到下载连接，然后用某雷svip才能链接上资源下载
> 
> which link？ I just access this website, there is no this file [/pile_neox/data/BookCorpusDataset_text_document.bin](https://the-eye.eu/public/AI/pile_neox/data/BookCorpusDataset_text_document.bin)

It's still this link, [https://the-eye.eu/public/AI/pile_neox/data/BookCorpusDataset_text_document.bin](url)
But I used Xunlei(China) to add the link and download it. 
So I think using the general download software to add a link can download, do not directly jump to this link to download. I think this is a bug caused by a change in the architecture of the Website page but the database behind the site didn't remove it

**Comment by loadams** [comment] 2023-12-12 21:36
Correct, this looks to be related to the website the data is hosted on and not Megatron-DeepSpeed.  Closing this issue for now, but using the updated link above should work.

**Closed by loadams** 2023-12-12 21:36 UTC

**Comment by lonelydancer** [comment] 2024-01-03 06:44
who knows how the file generated?  I wanna to fake one, i can't download that too.

**Comment by lonelydancer** [comment] 2024-01-03 07:19
> who knows how the file generated? I wanna to fake one, i can't download that too.

python tools/preprocess_data.py \
       --input my-corpus.json \
       --output-prefix my-gpt2 \
       --vocab-file gpt2-vocab.json \
       --dataset-impl mmap \
       --tokenizer-type GPT2BPETokenizer \
       --merge-file gpt2-merges.txt \
       --append-eod
